import React, { createContext, useContext, useState, useCallback } from 'react';

const LanguageContext = createContext();

const translations = {
  ka: {
    home: 'მთავარი',
    tours: 'ტურები',
    transfers: 'ტრანსფერები',
    contact: 'კონტაქტი',
    driverPanel: 'მძღოლის პანელი',
    adminPanel: 'ადმინ პანელი',
    signOut: 'გასვლა',
    signIn: 'შესვლა',
    
    heroTitle: 'ტრანსფერები და ტურები საქართველოში',
    heroSubtitle: 'ადგილობრივი მძღოლები, საუკეთესო ფასები',
    startLocation: 'საიდან',
    endLocation: 'სად',
    addStop: 'გაჩერების დამატება',
    date: 'თარიღი',
    time: 'დრო',
    searchCars: 'მანქანის მოძებნა',
    
    noFees: 'ფარული გადასახადების გარეშე',
    freeCancel: 'უფასო გაუქმება',
    englishDrivers: 'ინგლისურენოვანი მძღოლები',
    unlimitedStops: 'ულიმიტო გაჩერებები',
    verifiedDrivers: 'ვერიფიცირებული მძღოლები',
    support247: '24/7 მხარდაჭერა',
    noFeesDesc: 'გამჭვირვალე ფასები ფარული გადასახადების გარეშე.',
    freeCancelDesc: 'მოქნილი ჯავშნები უფასო გაუქმებით 24 საათით ადრე.',
    englishDriversDesc: 'კომუნიკაცია მარტივია ინგლისურენოვან მძღოლებთან.',
    verifiedDriversDesc: 'ყველა მძღოლი შემოწმებულია უსაფრთხოებისა და პროფესიონალიზმისთვის.',
    support247Desc: 'ჩვენ მზად ვართ დაგეხმაროთ ნებისმიერ დროს საქართველოში.',
    
    howItWorks: 'როგორ მუშაობს?',
    step1: 'აირჩიეთ მარშრუტი',
    step2: 'ჩვენ დავითვლით მანძილს',
    step3: 'აირჩიეთ მძღოლი',
    step4: 'დატოვეთ საკონტაქტო ინფორმაცია',
    step5: 'მძღოლი დაადასტურებს',
    step6: 'ისიამოვნეთ მგზავრობით',
    
    popularDestinations: 'პოპულარული მიმართულებები',
    bookNow: 'დაჯავშნა',
    readMore: 'ვრცლად',
    
    benefitsTitle: 'ჩვენი უპირატესობები',
    benefit1: 'ზუსტი ფასი წინასწარ',
    benefit2: 'სანდო ვერიფიცირებული მძღოლები',
    benefit3: 'უფასო ლოდინის დრო',
    benefit4: 'გაჩერებები დამატებითი საფასურის გარეშე',
    
    followUs: 'გამოგვყევით ინსტაგრამზე',
    planTrip: 'დაგეგმე შენი მოგზაურობა',
    readyToExplore: 'მზად ხართ საქართველოს დასათვალიერებლად?',
    
    firstName: 'სახელი',
    phone: 'ტელეფონი',
    email: 'ელ. ფოსტა',
    comment: 'კომენტარი',
    availableCars: 'ხელმისაწვდომი მანქანები',
    seats: 'ადგილი',

    // Admin Panel
    admin_dashboard: 'მართვის პანელი',
    admin_overview: 'პლატფორმის აქტივობის მიმოხილვა',
    admin_transferBookings: 'ტრანსფერ ჯავშნები',
    admin_tourBookings: 'ტურ ჯავშნები',
    admin_activeVehicles: 'აქტიური მანქანები',
    admin_registeredDrivers: 'რეგისტრირებული მძღოლები',
    admin_totalFleet: 'სულ ავტოპარკი',
    admin_vehiclesPending: 'მანქანა ელოდება განხილვას',
    admin_goToCars: 'გადადით მანქანებზე დასადასტურებლად',
    admin_driversAwaiting: 'მძღოლი ელოდება დადასტურებას',
    admin_goToDrivers: 'გადადით მძღოლებზე განხილვისთვის',
    admin_drivers: 'მძღოლები',
    admin_allDrivers: 'ყველა მძღოლი',
    admin_bookings: 'ჯავშნები',
    admin_allBookings: 'ყველა ჯავშანი',
    admin_finances: 'ფინანსები',
    admin_driverEarnings: 'მძღოლის შემოსავალი',
    admin_financialOverview: 'ფინანსური მიმოხილვა',
    admin_tours: 'ტურები',
    admin_allTours: 'ყველა ტური',
    admin_tourBookingsMenu: 'ტურ ჯავშნები',
    admin_cars: 'მანქანები',
    admin_transfers: 'ტრანსფერები',
    admin_locations: 'ლოკაციები',
    admin_contentManagement: 'კონტენტის მართვა',
    admin_siteContent: 'საიტის კონტენტი',
    admin_heroSection: 'მთავარი სექცია',
    admin_aboutPage: 'ჩვენ შესახებ',
    admin_smsSettings: 'SMS პარამეტრები',
    admin_settings: 'პარამეტრები',
    admin_logout: 'გამოსვლა',
    admin_pricing: 'ფასები',
    admin_search: 'ძიება',
    admin_status: 'სტატუსი',
    admin_actions: 'მოქმედებები',
    admin_vehicle: 'მანქანა',
    admin_driver: 'მძღოლი',
    admin_specs: 'სპეციფიკაცია',
    admin_customer: 'კლიენტი',
    admin_route: 'მარშრუტი',
    admin_driverAndCar: 'მძღოლი და მანქანა',
    admin_language: 'ენა',
  },
  en: {
    home: 'Home',
    tours: 'Tours',
    transfers: 'Transfers',
    contact: 'Contact',
    driverPanel: 'Driver Panel',
    adminPanel: 'Admin Panel',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    
    heroTitle: 'Transfers and tours around Georgia',
    heroSubtitle: 'From private drivers at the best prices',
    startLocation: 'Pick-up',
    endLocation: 'Drop-off',
    addStop: 'Add stop',
    date: 'Date',
    time: 'Time',
    searchCars: 'Find car',
    
    noFees: 'No hidden fees',
    freeCancel: 'Free cancellation',
    englishDrivers: 'English-speaking drivers',
    unlimitedStops: 'Unlimited stops',
    verifiedDrivers: 'Verified Drivers',
    support247: '24/7 Support',
    noFeesDesc: 'Transparent pricing with no hidden charges or surprises.',
    freeCancelDesc: 'Flexible bookings with free cancellation up to 24 hours.',
    englishDriversDesc: 'Communication is easy with our English-speaking drivers.',
    verifiedDriversDesc: 'Every driver is vetted for safety and professionalism.',
    support247Desc: 'We are here to help you anytime, anywhere in Georgia.',
    
    howItWorks: 'How it works?',
    step1: 'Choose your route',
    step2: 'We calculate distance',
    step3: 'Choose your driver',
    step4: 'Leave contact info',
    step5: 'Driver confirms',
    step6: 'Enjoy your ride',
    
    popularDestinations: 'Popular Destinations',
    bookNow: 'Book now',
    readMore: 'Read more',
    
    benefitsTitle: 'Our Benefits',
    benefit1: 'Accurate price upfront',
    benefit2: 'Reliable verified drivers',
    benefit3: 'Free waiting time',
    benefit4: 'Stops without extra fees',
    
    followUs: 'Follow us on Instagram',
    planTrip: 'Plan your trip',
    readyToExplore: 'Ready to explore Georgia?',
    
    firstName: 'First Name',
    phone: 'Phone',
    email: 'Email',
    comment: 'Comment',
    availableCars: 'Available Cars',
    seats: 'Seats',

    // Admin Panel
    admin_dashboard: 'Dashboard',
    admin_overview: 'Overview of your platform activity',
    admin_transferBookings: 'Transfer Bookings',
    admin_tourBookings: 'Tour Bookings',
    admin_activeVehicles: 'Active Vehicles',
    admin_registeredDrivers: 'Registered Drivers',
    admin_totalFleet: 'total fleet',
    admin_vehiclesPending: 'vehicles pending review',
    admin_goToCars: 'Go to Cars to approve or reject',
    admin_driversAwaiting: 'drivers awaiting approval',
    admin_goToDrivers: 'Go to Drivers to review applications',
    admin_drivers: 'Drivers',
    admin_allDrivers: 'All Drivers',
    admin_bookings: 'Bookings',
    admin_allBookings: 'All Bookings',
    admin_finances: 'Finances',
    admin_driverEarnings: 'Driver Earnings',
    admin_financialOverview: 'Financial Overview',
    admin_tours: 'Tours',
    admin_allTours: 'All Tours',
    admin_tourBookingsMenu: 'Tour Bookings',
    admin_cars: 'Cars',
    admin_transfers: 'Transfers',
    admin_locations: 'Locations',
    admin_contentManagement: 'Content Management',
    admin_siteContent: 'Site Content',
    admin_heroSection: 'Hero Section',
    admin_aboutPage: 'About Page',
    admin_smsSettings: 'SMS Settings',
    admin_settings: 'Settings',
    admin_logout: 'Logout',
    admin_pricing: 'Pricing',
    admin_search: 'Search',
    admin_status: 'Status',
    admin_actions: 'Actions',
    admin_vehicle: 'Vehicle',
    admin_driver: 'Driver',
    admin_specs: 'Specs',
    admin_customer: 'Customer',
    admin_route: 'Route',
    admin_driverAndCar: 'Driver & Car',
    admin_language: 'Language',
  },
  ru: {
    home: 'Главная',
    tours: 'Туры',
    transfers: 'Трансферы',
    contact: 'Контакты',
    driverPanel: 'Кабинет водителя',
    adminPanel: 'Админ панель',
    signOut: 'Выйти',
    signIn: 'Войти',
    
    heroTitle: 'Трансферы и туры по Грузии',
    heroSubtitle: 'От частных водителей по лучшим ценам',
    startLocation: 'Откуда',
    endLocation: 'Куда',
    addStop: 'Добавить остановку',
    date: 'Дата',
    time: 'Время',
    searchCars: 'Найти машину',
    
    noFees: 'Без скрытых комиссий',
    freeCancel: 'Бесплатная отмена',
    englishDrivers: 'Англоговорящие водители',
    unlimitedStops: 'Неограниченные остановки',
    verifiedDrivers: 'Проверенные водители',
    support247: 'Поддержка 24/7',
    noFeesDesc: 'Прозрачные цены без скрытых платежей.',
    freeCancelDesc: 'Гибкие бронирования с бесплатной отменой за 24 часа.',
    englishDriversDesc: 'Легко общайтесь с нашими англоговорящими водителями.',
    verifiedDriversDesc: 'Каждый водитель проверен на безопасность и профессионализм.',
    support247Desc: 'Мы готовы помочь вам в любое время в Грузии.',
    
    howItWorks: 'Как это работает?',
    step1: 'Выберите маршрут',
    step2: 'Мы рассчитаем расстояние',
    step3: 'Выберите водителя',
    step4: 'Оставьте контакты',
    step5: 'Водитель подтвердит',
    step6: 'Наслаждайтесь поездкой',
    
    popularDestinations: 'Популярные направления',
    bookNow: 'Забронировать',
    readMore: 'Подробнее',
    
    benefitsTitle: 'Наши преимущества',
    benefit1: 'Точная цена заранее',
    benefit2: 'Надежные водители',
    benefit3: 'Бесплатное ожидание',
    benefit4: 'Остановки без доплат',
    
    followUs: 'Подписывайтесь на Instagram',
    planTrip: 'Спланировать поездку',
    readyToExplore: 'Готовы исследовать Грузию?',
    
    firstName: 'Имя',
    phone: 'Телефон',
    email: 'Email',
    comment: 'Комментарий',
    availableCars: 'Доступные автомобили',
    seats: 'Мест',

    // Admin Panel
    admin_dashboard: 'Панель управления',
    admin_overview: 'Обзор активности платформы',
    admin_transferBookings: 'Бронирования трансферов',
    admin_tourBookings: 'Бронирования туров',
    admin_activeVehicles: 'Активные автомобили',
    admin_registeredDrivers: 'Зарегистрированные водители',
    admin_totalFleet: 'всего автомобилей',
    admin_vehiclesPending: 'автомобилей на рассмотрении',
    admin_goToCars: 'Перейдите в Автомобили для одобрения',
    admin_driversAwaiting: 'водителей ожидают одобрения',
    admin_goToDrivers: 'Перейдите в Водители для рассмотрения',
    admin_drivers: 'Водители',
    admin_allDrivers: 'Все водители',
    admin_bookings: 'Бронирования',
    admin_allBookings: 'Все бронирования',
    admin_finances: 'Финансы',
    admin_driverEarnings: 'Заработок водителей',
    admin_financialOverview: 'Финансовый обзор',
    admin_tours: 'Туры',
    admin_allTours: 'Все туры',
    admin_tourBookingsMenu: 'Бронирования туров',
    admin_cars: 'Автомобили',
    admin_transfers: 'Трансферы',
    admin_locations: 'Локации',
    admin_contentManagement: 'Управление контентом',
    admin_siteContent: 'Контент сайта',
    admin_heroSection: 'Главный баннер',
    admin_aboutPage: 'О нас',
    admin_smsSettings: 'Настройки SMS',
    admin_settings: 'Настройки',
    admin_logout: 'Выйти',
    admin_pricing: 'Цены',
    admin_search: 'Поиск',
    admin_status: 'Статус',
    admin_actions: 'Действия',
    admin_vehicle: 'Автомобиль',
    admin_driver: 'Водитель',
    admin_specs: 'Характеристики',
    admin_customer: 'Клиент',
    admin_route: 'Маршрут',
    admin_driverAndCar: 'Водитель и авто',
    admin_language: 'Язык',
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    try { return localStorage.getItem('georgiantrip-lang') || 'en'; } catch { return 'en'; }
  });
  
  const t = useCallback((key) => {
    return translations[currentLanguage]?.[key] || translations['en']?.[key] || key;
  }, [currentLanguage]);
  
  const changeLanguage = useCallback((lang) => {
    setCurrentLanguage(lang);
    try { localStorage.setItem('georgiantrip-lang', lang); } catch {}
  }, []);
  
  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};